import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "@mui/material";
import { bseenTheme } from "@/app/theme";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html>
        <body>
          <ThemeProvider theme={bseenTheme}>
            {children}
          </ThemeProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
